/*
 * Bhavcopy API
 * API to query Bhavcopy data.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kamlesh.bhavcopy.dto;

public class CopyQueryRequest {
    private String symbol;
    private String field;

    // Default constructor (required for serialization/deserialization)
    public CopyQueryRequest() {
    }

    // Constructor with parameters
    public CopyQueryRequest(String symbol, String field) {
        this.symbol = symbol;
        this.field = field;
    }

    // Getters and setters
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }
}
